
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Thu Mar 05 09:17:11 CET 2020
//----------------------------------------------------

package cmp20parser;

/** CUP generated interface containing symbol constants. */
public interface sym {
  /* terminals */
  public static final int GTEQUAL = 38;
  public static final int STRING_LITERAL = 50;
  public static final int LTEQUAL = 37;
  public static final int LOG_OR = 40;
  public static final int SEMI = 33;
  public static final int REF = 17;
  public static final int NOT = 15;
  public static final int LT = 36;
  public static final int RPAR = 22;
  public static final int IN = 19;
  public static final int COMMA = 25;
  public static final int CLASS = 3;
  public static final int FI = 11;
  public static final int BEGIN = 4;
  public static final int MULOP = 27;
  public static final int TYPE_INT = 44;
  public static final int ASSIGN = 43;
  public static final int IF = 8;
  public static final int EXP = 31;
  public static final int ID = 48;
  public static final int DOT = 26;
  public static final int EOF = 0;
  public static final int OD = 14;
  public static final int RETURN = 6;
  public static final int NEW = 16;
  public static final int error = 1;
  public static final int PROGRAM = 2;
  public static final int LCURLY = 23;
  public static final int NULL = 53;
  public static final int TYPE_FLOAT = 45;
  public static final int EQ = 34;
  public static final int ADDOP = 29;
  public static final int RCURLY = 24;
  public static final int COLON = 32;
  public static final int ELSE = 10;
  public static final int TYPE_STRING = 46;
  public static final int WHILE = 12;
  public static final int NEQUAL = 41;
  public static final int DIVOP = 28;
  public static final int THEN = 9;
  public static final int LOG_AND = 39;
  public static final int END = 5;
  public static final int LPAR = 21;
  public static final int FLOAT_LITERAL = 49;
  public static final int SUBOP = 30;
  public static final int TYPE_BOOL = 47;
  public static final int STRUCT = 20;
  public static final int GT = 35;
  public static final int VAR = 42;
  public static final int DEREF = 18;
  public static final int PROCEDURE = 7;
  public static final int BOOL_LITERAL = 52;
  public static final int DO = 13;
  public static final int INT_LITERAL = 51;
}

