
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Thu Mar 05 19:37:23 GMT 2020
//----------------------------------------------------

package parser;

/** CUP generated interface containing symbol constants. */
public interface sym {
  /* terminals */
  public static final int GTEQUAL = 37;
  public static final int STRING_LITERAL = 49;
  public static final int LTEQUAL = 36;
  public static final int LOG_OR = 39;
  public static final int SEMI = 32;
  public static final int REF = 16;
  public static final int NOT = 14;
  public static final int LT = 35;
  public static final int RPAR = 21;
  public static final int IN = 18;
  public static final int COMMA = 24;
  public static final int FI = 10;
  public static final int BEGIN = 3;
  public static final int MULOP = 26;
  public static final int TYPE_INT = 43;
  public static final int ASSIGN = 42;
  public static final int IF = 7;
  public static final int EXP = 30;
  public static final int ID = 47;
  public static final int DOT = 25;
  public static final int EOF = 0;
  public static final int OD = 13;
  public static final int RETURN = 5;
  public static final int NEW = 15;
  public static final int error = 1;
  public static final int PROGRAM = 2;
  public static final int LCURLY = 22;
  public static final int NULL = 52;
  public static final int TYPE_FLOAT = 44;
  public static final int EQ = 33;
  public static final int ADDOP = 28;
  public static final int RCURLY = 23;
  public static final int COLON = 31;
  public static final int ELSE = 9;
  public static final int TYPE_STRING = 45;
  public static final int WHILE = 11;
  public static final int NEQUAL = 40;
  public static final int DIVOP = 27;
  public static final int THEN = 8;
  public static final int LOG_AND = 38;
  public static final int END = 4;
  public static final int LPAR = 20;
  public static final int FLOAT_LITERAL = 48;
  public static final int SUBOP = 29;
  public static final int TYPE_BOOL = 46;
  public static final int STRUCT = 19;
  public static final int GT = 34;
  public static final int VAR = 41;
  public static final int DEREF = 17;
  public static final int PROCEDURE = 6;
  public static final int BOOL_LITERAL = 51;
  public static final int DO = 12;
  public static final int INT_LITERAL = 50;
}

